package Pantallas.LogIn;

import General.*;
import java.util.ArrayList;

public class LogIn extends javax.swing.JFrame {

    private ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();
    private ArrayList<Profesor> listaProfesores = new ArrayList<>();
    private ArrayList<Materia> Materia = new ArrayList<>();

    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Materia = new ArrayList<>(); // <- Agrega esto al constructor de Materia
        this.listaEstudiantes = new ArrayList<>();
        this.listaProfesores = new ArrayList<>();
        inicializarDatos();
    }

    private void inicializarDatos() {
        // Materias compartidas
        Materia m1 = new Materia("MAT101", "Matemática 1", "Ingeniería", "8:00-10:00", "01", "P1");
        Materia m2 = new Materia("PRO102", "Programación", "Ingeniería", "10:00-12:00", "01", "P2");
        Materia m3 = new Materia("ING103", "Inglés", "Idiomas", "12:00-2:00", "01", "P3");

        // Profesores 1 a 3 con materias compartidas
        Profesor prof1 = new Profesor("P1", "María Jiménez", "mjimenez@ulacit.ed.cr", "1234");
        prof1.getMaterias().add(m1);

        Profesor prof2 = new Profesor("P2", "Carlos Mora", "cmora@ulacit.ed.cr", "1234");
        prof2.getMaterias().add(m2);

        Profesor prof3 = new Profesor("P3", "Laura Quesada", "lquesada@ulacit.ed.cr", "1234");
        prof3.getMaterias().add(m3);

        listaProfesores.add(prof1);
        listaProfesores.add(prof2);
        listaProfesores.add(prof3);

        // Profesores 4 a 10 con materias diferentes
        for (int i = 4; i <= 10; i++) {
            String id = "P" + i;
            String nombre = "Profesor " + i;
            String correo = "prof" + i + "@ulacit.ed.cr";
            String contra = "1234";

            Profesor p = new Profesor(id, nombre, correo, contra);
            Materia nuevaMateria = new Materia("MAT" + i + "00", "Curso " + i, "Carrera X", "1:00-3:00", "0" + i, id);
            p.getMaterias().add(nuevaMateria);

            listaProfesores.add(p);
        }

        // Estudiantes 1 a 20 con las 3 materias compartidas
        for (int i = 1; i <= 20; i++) {
            String id = "E" + i;
            String nombre = "Estudiante " + i;
            String correo = "est" + i + "@ulacit.ed.cr";
            String contra = "1234";

            Estudiante e = new Estudiante(id, nombre, correo, contra);

            // Agregar materias
            e.getMaterias().add(m1);
            e.getMaterias().add(m2);
            e.getMaterias().add(m3);

            // Agregar estudiante a las materias
            m1.agregarEstudiante(e);
            m2.agregarEstudiante(e);
            m3.agregarEstudiante(e);

            listaEstudiantes.add(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        LabelLogoULACIT = new javax.swing.JLabel();
        Label_Bienvenido = new javax.swing.JLabel();
        btn_Profesor = new javax.swing.JButton();
        btn_Estudiante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_estudiante2 = new javax.swing.JButton();
        btn_Profesor2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(63, 42, 85));

        LabelLogoULACIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo Ulacit.png"))); // NOI18N

        Label_Bienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Label_Bienvenido.setText("Bienvenido a ");

        btn_Profesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenProfesor.jpg"))); // NOI18N
        btn_Profesor.setText("Profesor");
        btn_Profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfesorActionPerformed(evt);
            }
        });

        btn_Estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenEstudiante.jpg"))); // NOI18N
        btn_Estudiante.setText("Estudiante");
        btn_Estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstudianteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("canvas");

        btn_estudiante2.setBackground(new java.awt.Color(102, 102, 255));
        btn_estudiante2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_estudiante2.setForeground(new java.awt.Color(0, 0, 0));
        btn_estudiante2.setText("Estudiante");
        btn_estudiante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudiante2ActionPerformed(evt);
            }
        });

        btn_Profesor2.setBackground(new java.awt.Color(102, 102, 255));
        btn_Profesor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Profesor2.setForeground(new java.awt.Color(0, 0, 0));
        btn_Profesor2.setText("Profesor");
        btn_Profesor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Profesor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelLogoULACIT)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(Label_Bienvenido)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_estudiante2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Profesor2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelLogoULACIT)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_Bienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_estudiante2)
                    .addComponent(btn_Profesor2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstudianteActionPerformed
        // TODO add your handling code here:
        LoginEstudiante loginest = new LoginEstudiante(listaEstudiantes);
        loginest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EstudianteActionPerformed

    private void btn_ProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfesorActionPerformed
        // TODO add your handling code here:
        LoginProfesor loginprofe = new LoginProfesor(listaProfesores);
        loginprofe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ProfesorActionPerformed

    private void btn_estudiante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudiante2ActionPerformed
        // TODO add your handling code here:
        LoginEstudiante loginest = new LoginEstudiante();
        loginest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_estudiante2ActionPerformed

    private void btn_Profesor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Profesor2ActionPerformed
        // TODO add your handling code here:
        LoginProfesor loginprofe = new LoginProfesor();
        loginprofe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Profesor2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogoULACIT;
    private javax.swing.JLabel Label_Bienvenido;
    private javax.swing.JButton btn_Estudiante;
    private javax.swing.JButton btn_Profesor;
    private javax.swing.JButton btn_Profesor2;
    private javax.swing.JButton btn_estudiante2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
