package CursoProfesor;

import General.Materia;
import General.Modulo;
import General.Sistema;
import javax.swing.JOptionPane;

public class JAgregarModulo extends javax.swing.JFrame {

    private Materia materiaActual;
    private ModuloProfesor ventanaPrincipal;
    // Para saber cual hay que editar
    private Modulo moduloAEditar;

    // CONSTRUCTOR PARA AGREGAR UN NUEVO MÓDULO
    public JAgregarModulo(Materia materiaActual, ModuloProfesor ventanaPrincipal) {
        this.materiaActual = materiaActual;
        this.ventanaPrincipal = ventanaPrincipal;
        this.moduloAEditar = null; // En este no hay modulo actual
        initComponents();
        this.setLocationRelativeTo(null);
        // paraque salga como si fuera a crear uno
        jButton1.setText("Agregar");
    }
    
    // NUEVO CONSTRUCTOR PARA EDITAR UN MÓDULO QUE YA EXISTE
    public JAgregarModulo(Modulo modulo, ModuloProfesor ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        this.moduloAEditar = modulo; // Guarda el módulo a editar
        this.materiaActual = null;
        initComponents();
        this.setLocationRelativeTo(null);
        // llena el campo con el nombre anterior
        JTF_NombreModulo.setText(modulo.getTitulo());
        // Para que salga como si fuera a editar
        jButton1.setText("Guardar Cambios");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTF_NombreModulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("AGREGAR MODULO O EDITAR");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JTF_NombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(JTF_NombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreModulo = JTF_NombreModulo.getText().trim();
        if (nombreModulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del módulo no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Logica para EDITAR un módulo
        if (this.moduloAEditar != null) {
            this.moduloAEditar.setTitulo(nombreModulo);
            JOptionPane.showMessageDialog(this, "Módulo editado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } 
        // Logica para AGREGAR un nuevo módulo
        else {
            Modulo nuevoModulo = new Modulo(nombreModulo);
            materiaActual.agregarModulo(nuevoModulo);
            JOptionPane.showMessageDialog(this, "Módulo agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // Llama al metodo de la ventana principal para que se actualice y luego cierra la ventana
        ventanaPrincipal.cargarModulos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTF_NombreModulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
