package CursoProfesor;

import General.ArchivoAsistencias;
import General.Asistencia;
import General.Estudiante;
import General.Materia;
import General.Sistema;
import General.VentanaPrincipalProfesor;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

public class JAsistencia extends javax.swing.JFrame {
    /*
            - Nota Developer 1:
        Frame para ver las asistencias
        this.setLocationRelativeTo(null); hace que la ventana se inicie en el centro

        Después hay botones/labels que permiten moverse a otros frames de la parte de CursoProfesor
        se debe de pasar siempre la materia por el constructor de cada frame
    */
    private Materia mate; //para manener la materia actual
    private HashMap<String, String> asistenciaMap = new HashMap<>();
    //Constructor
    public JAsistencia(Materia mate) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mate = mate;
        cargarTablaAsistencia();
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Tablero = new javax.swing.JLabel();
        jLabel_Cursos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnGuardar = new javax.swing.JButton();
        BtnVerAsistencias = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Menupop = new javax.swing.JPanel();
        jLabel_Modulos = new javax.swing.JLabel();
        jLabel_Anuncios = new javax.swing.JLabel();
        jLabel_PagInicio = new javax.swing.JLabel();
        jLabel_Asignaciones = new javax.swing.JLabel();
        jLabel_Calificaciones = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_Grupos = new javax.swing.JLabel();
        jLabel_Asistencias = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAsistencia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 42, 85));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo Ulacit_vSmall.png"))); // NOI18N

        jLabel_Tablero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Tablero.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tablero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tablero.setText("Tablero");
        jLabel_Tablero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TableroMouseClicked(evt);
            }
        });

        jLabel_Cursos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Cursos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Cursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cursos.setText("Cursos");
        jLabel_Cursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CursosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1586, 1885));
        jPanel2.setName(""); // NOI18N

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Editar");
        jButton2.setBorder(null);

        jLabel1.setText("Asistencias");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnVerAsistencias.setText("Ver Asistencias");
        BtnVerAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAsistenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGuardar)
                .addGap(26, 26, 26)
                .addComponent(BtnVerAsistencias)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnVerAsistencias))
                .addGap(237, 237, 237))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Menupop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Modulos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Modulos.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Modulos.setText("Modulos");
        jLabel_Modulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Modulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ModulosMouseClicked(evt);
            }
        });

        jLabel_Anuncios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Anuncios.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Anuncios.setText("Anuncios");
        jLabel_Anuncios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Anuncios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AnunciosMouseClicked(evt);
            }
        });

        jLabel_PagInicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_PagInicio.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_PagInicio.setText("Pagina inicio");
        jLabel_PagInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_PagInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PagInicioMouseClicked(evt);
            }
        });

        jLabel_Asignaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Asignaciones.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Asignaciones.setText("Asignaciones");
        jLabel_Asignaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Asignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AsignacionesMouseClicked(evt);
            }
        });

        jLabel_Calificaciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Calificaciones.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Calificaciones.setText("Calificaciones");
        jLabel_Calificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Calificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CalificacionesMouseClicked(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_Grupos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Grupos.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_Grupos.setText("Grupos");
        jLabel_Grupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_GruposMouseClicked(evt);
            }
        });

        jLabel_Asistencias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Asistencias.setForeground(new java.awt.Color(63, 42, 85));
        jLabel_Asistencias.setText("Asistencias");
        jLabel_Asistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout MenupopLayout = new javax.swing.GroupLayout(Menupop);
        Menupop.setLayout(MenupopLayout);
        MenupopLayout.setHorizontalGroup(
            MenupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenupopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Asistencias)
                    .addComponent(jLabel_Grupos)
                    .addComponent(jLabel_Anuncios)
                    .addComponent(jLabel_Modulos)
                    .addComponent(jLabel_Asignaciones)
                    .addComponent(jLabel_Calificaciones)
                    .addComponent(jLabel_PagInicio))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        MenupopLayout.setVerticalGroup(
            MenupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenupopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel_PagInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Anuncios)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Modulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Asignaciones)
                .addGap(15, 15, 15)
                .addComponent(jLabel_Calificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Grupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Asistencias)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hmenu.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Menupop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Menupop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Asistencias");

        jLabel4.setText("No se ha escrito una descripción");

        tablaAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Presente", "Ausente", "Tarde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaAsistencia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(722, 722, 722)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Botnoes-------------------------------------------------------------

    // Método que carga la tabla de asistencia con los estudiantes
    private void cargarTablaAsistencia() {
        DefaultTableModel modelo = (DefaultTableModel) tablaAsistencia.getModel();

        // Limpia todas las filas anteriores (para evitar duplicados)
        modelo.setRowCount(0);

        // Verifica que la tabla tenga al menos 5 columnas (Nombre, ID, Presente, Ausente, Tarde)
        if (tablaAsistencia.getColumnCount() < 5) {
            System.err.println("La tabla no tiene las columnas necesarias para botones.");
            return; // Sale del método si no hay columnas suficientes
        }

        // Crear una lista con todos los estudiantes (con grupo y sin grupo)
        ArrayList<Estudiante> todos = new ArrayList<>();
        todos.addAll(mate.getEstudiantes());
        todos.addAll(mate.getEstudiantesSinGrupo());

        // Agregar una fila por cada estudiante con su nombre, ID y columnas vacías para los botones
        for (Estudiante est : todos) {
            modelo.addRow(new Object[]{est.getNombre(), est.getId(), "", "", ""});
        }

        // Configurar los botones en las columnas de asistencia (Presente, Ausente, Tarde)
        TableColumnModel columnModel = tablaAsistencia.getColumnModel();
        for (int i = 2; i <= 4; i++) {
            BotonRendererEditor editor = new BotonRendererEditor(tablaAsistencia, asistenciaMap);
            columnModel.getColumn(i).setCellRenderer(editor); // Renderiza el botón en la celda
            columnModel.getColumn(i).setCellEditor(editor);   // Permite que el botón sea clickeable
        }
    }

    // Método para obtener la fecha que el usuario ingresa
    private Date obtenerFechaSeleccionada() {
        // Pedir la fecha al usuario
        String textoFecha = JOptionPane.showInputDialog(this, "Ingrese la fecha (dd/MM/yy):");
        if (textoFecha == null || textoFecha.trim().isEmpty()) return null;

        // Configurar el formato de fecha válido
        SimpleDateFormat formatoCR = new SimpleDateFormat("dd/MM/yy");
        formatoCR.setLenient(false); // No permite fechas inválidas como 32/01/23
        try {
            return formatoCR.parse(textoFecha.trim()); // Convertir el texto a Date
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato inválido. Use dd/MM/yy", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    // Clase interna que maneja los botones de la tabla
    public class BotonRendererEditor extends AbstractCellEditor implements TableCellRenderer, TableCellEditor, ActionListener {
        private final JButton button = new JButton(); // Botón que se mostrará en la celda
        private final JTable table;
        private String estado; // Guarda el estado seleccionado (Presente, Ausente, Tarde)
        private int currentColumn;
        private final HashMap<String, String> asistenciaMap; // Mapa que guarda asistencia por ID

        // Constructor: recibe la tabla y el mapa de asistencias
        public BotonRendererEditor(JTable table, HashMap<String, String> asistenciaMap) {
            this.table = table;
            this.asistenciaMap = asistenciaMap;
            button.addActionListener(this); // Asigna acción al botón
            button.setFocusPainted(false); // Estilo visual
        }

        // Configura el botón según la columna en la que esté
        private void configurarBoton(int column) {
            currentColumn = column;
            switch (column) {
                case 2 -> { // Columna "Presente"
                    button.setText("✔");
                    button.setBackground(Color.GREEN);
                    estado = "Presente";
                }
                case 3 -> { // Columna "Ausente"
                    button.setText("✘");
                    button.setBackground(Color.RED);
                    estado = "Ausente";
                }
                case 4 -> { // Columna "Tarde"
                    button.setText("⏰");
                    button.setBackground(Color.ORANGE);
                    estado = "Tarde";
                }
            }
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            configurarBoton(column);
            return button;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            configurarBoton(column);
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return estado;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            int row = table.getSelectedRow();
            if (row != -1) {
                String id = table.getValueAt(row, 1).toString(); // Obtener ID del estudiante
                asistenciaMap.put(id, estado); // Guardar su estado en el mapa
            }
            fireEditingStopped(); // Detener edición en la celda
        }
    }

    /**
     -------                                                                     ----------
     Labels que sirven como botones, los cuales llevan a otras "pestañas" de CursoEstudiante
     En todos se crea un objeto del frame, se pone visible y se cierra la ventana actual
     -------                                                                     ----------
     */
    //Para ir a la principal
    private void jLabel_TableroMouseClicked(java.awt.event.MouseEvent evt) {
        VentanaPrincipalProfesor VPE = new VentanaPrincipalProfesor();
        VPE.setVisible(true);
        this.dispose(); // Cierra esta ventana
    }
    //No está hecho aún
    private void jLabel_CursosMouseClicked(java.awt.event.MouseEvent evt) {

    }
    //para ir a modulos
    private void jLabel_ModulosMouseClicked(java.awt.event.MouseEvent evt) {
        JModuloProfesor mp = new JModuloProfesor(mate);
        mp.setVisible(true);
        this.dispose();
    }
    //Todavia no esta
    private void jLabel_AnunciosMouseClicked(java.awt.event.MouseEvent evt) {

    }
    //Para ir a la pagina de inicio del curso
    private void jLabel_PagInicioMouseClicked(java.awt.event.MouseEvent evt) {
        CursoProfesor CursoP = new CursoProfesor(mate);
        CursoP.setVisible(true);
        this.dispose();
        // Redirige a otra pantalla
    }

    //Para ir a asignaciones
    private void jLabel_AsignacionesMouseClicked(java.awt.event.MouseEvent evt) {
        JCreaAsignaciones asignaciones = new JCreaAsignaciones(mate); // Ventana de asignaciones con la materia actual
        asignaciones.setVisible(true); // Se abre
        this.dispose(); // Se cierra la actual
    }

    //Para ir a calificaciones
    private void jLabel_CalificacionesMouseClicked(java.awt.event.MouseEvent evt) {
        JCalificacionesProfe califica = new JCalificacionesProfe(mate);
        califica.setVisible(true);
        this.dispose();
    }

    //para ir a grupos
    private void jLabel_GruposMouseClicked(java.awt.event.MouseEvent evt) {
        JGrupo grupo = new JGrupo(mate);
        grupo.setVisible(true);
        this.dispose();
    }

    //Para el menu desplegable
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {
        // Muestra u oculta el menú emergente
        if (!Menupop.isVisible()) {
            this.Menupop.setVisible(true);
        } else {
            this.Menupop.setVisible(false);
        }
    }

    // Botón "Guardar asistencia"
    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        Date fecha = obtenerFechaSeleccionada(); // Pedir fecha al usuario
        if (fecha == null) return;

        ArrayList<Asistencia> nuevas = new ArrayList<>();

        // Recorre cada fila de la tabla
        for (int i = 0; i < tablaAsistencia.getRowCount(); i++) {
            String id = tablaAsistencia.getValueAt(i, 1).toString();
            String estadoTexto = asistenciaMap.get(id);

            if (estadoTexto == null) {
                JOptionPane.showMessageDialog(this, "Falta marcar asistencia para todos los estudiantes");
                return;
            }

            // Convertir el texto del estado en un valor del enum EstadoAsistencia
            Asistencia.EstadoAsistencia estado;
            switch (estadoTexto) {
                case "Presente" -> estado = Asistencia.EstadoAsistencia.PRESENTE;
                case "Ausente" -> estado = Asistencia.EstadoAsistencia.AUSENTE;
                case "Tarde" -> estado = Asistencia.EstadoAsistencia.TARDE;
                default -> {
                    JOptionPane.showMessageDialog(this, "Estado inválido para el estudiante con ID: " + id);
                    continue;
                }
            }

            // Crear nueva asistencia y agregarla a la lista
            nuevas.add(new Asistencia(id, fecha, estado));
        }

        // Guardar asistencias en la materia
        for (Asistencia a : nuevas) {
            mate.agregarAsistencia(a);
        }

        // Persistir los datos en archivo
        ArchivoAsistencias.guardar(mate.getAsistencias());
        JOptionPane.showMessageDialog(this, "Asistencia guardada exitosamente");
    }

    // Botón "Ver asistencias guardadas"
    private void BtnVerAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Asistencia> lista = ArchivoAsistencias.cargar(); // Carga todas las asistencias

        if (lista == null || lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay asistencias registradas.");
            return;
        }

        StringBuilder resumen = new StringBuilder("Asistencias registradas para la materia " + mate.getNombre() + ":\n\n");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");

        // Recorre asistencias y muestra si corresponden a esta materia
        for (Asistencia a : lista) {
            if (mate.contieneEstudiante(a.getIdEstudiante())) {
                resumen.append("Estudiante ID: ").append(a.getIdEstudiante())
                        .append(" | Fecha: ").append(sdf.format(a.getFecha()))
                        .append(" | Estado: ").append(a.getEstado()).append("\n");
            }
        }

        // Si no se agregaron registros, mostrar mensaje
        if (resumen.toString().endsWith(":\n\n")) {
            resumen.append("No hay asistencias para esta materia.");
        }

        // Mostrar resumen en un cuadro de diálogo
        JOptionPane.showMessageDialog(this, resumen.toString(), "Asistencias Guardadas", JOptionPane.INFORMATION_MESSAGE);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVerAsistencias;
    private javax.swing.JPanel Menupop;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Anuncios;
    private javax.swing.JLabel jLabel_Asignaciones;
    private javax.swing.JLabel jLabel_Asistencias;
    private javax.swing.JLabel jLabel_Calificaciones;
    private javax.swing.JLabel jLabel_Cursos;
    private javax.swing.JLabel jLabel_Grupos;
    private javax.swing.JLabel jLabel_Modulos;
    private javax.swing.JLabel jLabel_PagInicio;
    private javax.swing.JLabel jLabel_Tablero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tablaAsistencia;
    // End of variables declaration//GEN-END:variables
}
